# Generated by Django 5.2.1 on 2025-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('specialist_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('availability', models.CharField(default='Mon-Fri 9:00 am - 12:00 pm', max_length=100)),
            ],
        ),
    ]
